experiment1:
  kd_loss:
    - "CS"
    - "KL"
    - "MS"
    - "TV"
    - "JS"
  alpha_st_pairs:
    - [0.5, 0.5]
    - [1.0, 0.5]
    - [0.7, 0.3]
    - [0.0, 0.5]
  student_teacher_pairs:
    - ["mobilenet_v3_small", "mobilenet_v3_small"]
  temperatures:
    - 6.0
  num_epochs:
    - [10, 10, 10]
    - [20, 5, 5]
    - [5, 20, 5]
    - [5, 5, 20]
    - [0, 15, 15]
    - [15, 15, 0]
    - [0, 30, 0]
  max_lr: 1e-3
  min_lr: 1e-6
  teacher_lr: 1e-6
  device: "cuda"
  batch_size: 64
  num_workers: 16
  traindir: "imageNet/train200"
  validdir: "imageNet/valid"
